#!/usr/bin/env bash
# ex2-verify.sh — spot-check Exam 2 persistence. Run with sudo on each host.
pass=0; fail=0
chk() { # chk "label" "command"
  if eval "$2" &>/dev/null; then printf '  \033[32mPASS\033[0m  %s\n' "$1"; pass=$((pass+1))
  else printf '  \033[31mFAIL\033[0m  %s\n' "$1"; fail=$((fail+1)); fi
}

echo "== Host: $(hostname -s) =="

case "$(hostname -s)" in
  *charlie*)
    chk "T3  audit=1 in cmdline"        "grep -q 'audit=1' /proc/cmdline"
    chk "T3  net.ifnames=0 in cmdline"  "grep -q 'net.ifnames=0' /proc/cmdline"
    chk "T3  quiet removed"             "! grep -q ' quiet' /proc/cmdline"
    chk "T4  hostname charlie"          "hostnamectl --static | grep -qx charlie.ex200.lab"
    chk "T4  IPv4 10.20.30.11"          "ip -4 addr show | grep -q '10.20.30.11'"
    chk "T4  IPv6 fd42::11"             "ip -6 addr show | grep -q 'fd42::11'"
    chk "T4  lab-static autoconnect"    "nmcli -g connection.autoconnect con show lab-static | grep -qi yes"
    chk "T5  labzone is default"        "firewall-cmd --get-default-zone | grep -qx labzone"
    chk "T5  labzone ports 9000-9010"   "firewall-cmd --zone=labzone --list-ports | grep -q 9000-9010"
    chk "T5  labzone has ssh"           "firewall-cmd --zone=labzone --list-services | grep -q ssh"
    chk "T6  emma uid 2100"             "id -u emma | grep -qx 2100"
    chk "T6  ops gid 6000"              "getent group ops | grep -q ':6000:'"
    chk "T6  emma home /srv/users/emma" "getent passwd emma | grep -q /srv/users/emma"
    chk "T6  henry nologin"             "getent passwd henry | grep -qE '(nologin|false)$'"
    chk "T7  pwquality minlen 12"       "grep -qE '^\\s*minlen\\s*=\\s*12' /etc/security/pwquality.conf"
    chk "T7  emma max 45 days"          "chage -l emma | grep -qi 'Maximum.*45'"
    chk "T8  sudoers valid"             "visudo -c &>/dev/null"
    chk "T8  lab_sudo has OPSTEAM"      "grep -q OPSTEAM /etc/sudoers.d/lab_sudo"
    chk "T9  phoenix 2770"              "stat -c '%a' /srv/project/phoenix | grep -qx 2770"
    chk "T9  frank access ACL"          "getfacl /srv/project/phoenix 2>/dev/null | grep -q '^user:frank:rwx'"
    chk "T9  default ACL present"       "getfacl /srv/project/phoenix 2>/dev/null | grep -q '^default:'"
    chk "T10 ops umask drop-in"         "grep -rq '0027' /etc/profile.d/"
    chk "T13 two repo files"            "test -f /etc/yum.repos.d/lab-baseos.repo -a -f /etc/yum.repos.d/lab-appstream.repo"
    chk "T13 gpgcheck enabled"          "grep -q 'gpgcheck=1' /etc/yum.repos.d/lab-baseos.repo"
    chk "T17 charliexfs mounted"        "findmnt /mnt/charliexfs"
    chk "T17 usbdata noexec"            "findmnt -no OPTIONS /mnt/usbdata | grep -q noexec"
    chk "T17 usbdata by LABEL"          "grep '/mnt/usbdata' /etc/fstab | grep -q 'LABEL=USBDATA'"
    chk "T19 vg_lab2 32M PE"            "vgs --noheadings -o vg_extent_size vg_lab2 | grep -q '32'"
    chk "T19 stripe mounted"            "findmnt /mnt/stripe"
    chk "T19 home2 mounted"             "findmnt /mnt/home2"
    chk "T20 vdd removed from VG"       "! pvs --noheadings -o pv_name | grep -q /dev/vdd"
    chk "T22 projects mounted"          "findmnt /mnt/projects"
    chk "T22 archive read-only"         "findmnt -no OPTIONS /mnt/archive | grep -q '\\bro\\b'"
    chk "T23 autofs enabled"            "systemctl is-enabled --quiet autofs"
    chk "T24 finance 2750 gina:ops"     "stat -c '%a %U:%G' /opt/finance | grep -qx '2750 gina:ops'"
    chk "T24 private 0700"              "stat -c '%a' /opt/finance/private | grep -qx 700"
    chk "T24 suid list saved"           "test -s /root/suid_list.txt"
    chk "T25 chrony uses delta"         "grep -qE '^server +delta' /etc/chrony.conf"
    chk "T25 timezone London"           "timedatectl show -p Timezone --value | grep -qx Europe/London"
    chk "T26 lab-highio active"         "tuned-adm active | grep -q lab-highio"
    chk "T26 swappiness 10"             "sysctl -n vm.swappiness | grep -qx 10"
    chk "T28 journal persistent"        "test -d /var/log/journal"
    chk "T28 ForwardToSyslog"           "grep -qE '^ForwardToSyslog=yes' /etc/systemd/journald.conf"
    chk "T28 secure.lab rule"           "grep -q 'secure.lab' /etc/rsyslog.conf /etc/rsyslog.d/* 2>/dev/null"
    chk "T28 logrotate config"          "test -f /etc/logrotate.d/secure.lab"
    chk "T29 labhealth timer enabled"   "systemctl is-enabled --quiet labhealth.timer"
    chk "T29 emma weekday cron"         "crontab -l -u emma 2>/dev/null | grep -q '1-5'"
    chk "T32 health_report cron"        "crontab -l 2>/dev/null | grep -q 'health_report.sh'"
    chk "T33 SELinux enforcing"         "getenforce | grep -qx Enforcing"
    chk "T33 websites labeled"          "ls -Zd /srv/websites | grep -q httpd_sys_content_t"
    chk "T33 site1 serving"             "curl -sf http://localhost/ | grep -q 'Site1 charlie'"
    chk "T34 port 2222 labeled"         "semanage port -l | grep ssh_port_t | grep -q 2222"
    chk "T34 sshd on 2222"              "ss -tlnp | grep -q ':2222'"
    chk "T34 labzone has 2222"          "firewall-cmd --zone=labzone --list-ports | grep -q 2222"
    chk "T34 container_manage_cgroup"   "getsebool container_manage_cgroup | grep -q ' on$'"
    ;;
  *delta*)
    chk "T2  default graphical"         "systemctl get-default | grep -qx graphical.target"
    chk "T4  hostname delta"            "hostnamectl --static | grep -qx delta.ex200.lab"
    chk "T4  IPv4 10.20.30.12"          "ip -4 addr show | grep -q '10.20.30.12'"
    chk "T4  IPv6 fd42::12"             "ip -6 addr show | grep -q 'fd42::12'"
    chk "T10 hard link demo"            "test -f /root/link_notes.txt"
    chk "T11 PermitRootLogin prohibit"  "sshd -T 2>/dev/null | grep -qi 'permitrootlogin prohibit-password'"
    chk "T11 AllowUsers set"            "grep -qE '^AllowUsers' /etc/ssh/sshd_config"
    chk "T11 sshd config valid"         "sshd -t"
    chk "T18 swap file active"          "swapon --show | grep -q /swap/extraswap.img"
    chk "T18 swap priority 20"          "swapon --show=PRIO --noheadings | grep -q 20"
    chk "T18 swapfile mode 0600"        "stat -c '%a' /swap/extraswap.img | grep -qx 600"
    chk "T21 nfs-server running"        "systemctl is-active --quiet nfs-server"
    chk "T21 nfsv3 disabled"            "grep -qE '^\\s*vers3\\s*=\\s*n' /etc/nfs.conf"
    chk "T21 projects exported"         "exportfs -v | grep -q /srv/nfs/projects"
    chk "T25 chrony allows subnet"      "grep -qE '^allow +10\\.20\\.30\\.0/24' /etc/chrony.conf"
    chk "T25 timezone Tokyo"            "timedatectl show -p Timezone --value | grep -qx Asia/Tokyo"
    ;;
esac

echo "== $pass passed, $fail failed =="
